pipeline{
    agent none

    environment{
        PYTHONBUFFERED='1'
    }

    stages{
        stage('Checkout Code'){
            agent any 
            steps {
                echo "Pulling code from github ..."
                checkout scm
            }
        }

        stage('Run tests'){
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '-u root'
                }
            }
            steps{
                echo 'Running pytest tests....'
                sh '''
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install pytest pytest-django pytest-cov

                    mkdir -p test-results

                    pytest --junit-xml=test-results/results.xml --cov=. --cov-report=html || true
                    '''
            }
        }

        stage('Generate Reports'){
            agent any 
            steps{
                echo "Publishing test results...."
                junit 'test-results/results.xml'

                publishHTML([
                    reportDIR: 'htmlcov',
                    reportFiles: 'index.html',
                    reportName: 'Coverage Report'
                ])
            }
        }
    }

    post {
        always{
            echo "cleaning up workspace...."
            cleanWs()
        }
        succes{
            echo "Pipeline completed successfully"
        }
        failure{
            echo "Pipeline failed - check logs above"
        }
    }
}