#!/bin/bash

# Scale Django app to 3 replicas
echo "scaling deployment to 3..."
kubectl scale deployment messaging-app --replicas=3

# Verify pods
echo "verifying running pods ....."
kubectl get pods

# Get service URL
echo "getting service url and packing it into the URL variable..."
URL=$(minikube service messaging-app-service --url)

# Load test with wrk
echo "testing the load to see it in action"
wrk -t2 -c20 -d30s $URL

# Monitor resource usage
echo "showing top pods ..."
kubectl top pods

