#!/bin/bash

# Deploy blue version
kubectl apply -f blue_deployment.yaml

# Deploy green version
kubectl apply -f green_deployment.yaml

# Apply service
kubectl apply -f kubeservice.yaml

# Check logs of green deployment for errors
kubectl logs -l app=messaging,version=green
