#!/bin/bash

echo "Checking if minikube is installed..."
if ! command -v minikube &> /dev/null
then 
    echo "Minikube is not installed, installing minikube first"
    exit 1
fi

echo "Minikube is installed"

echo "Starting kubernetes clusters with minikube..."
minikube start

echo "Verifying cluster status...."
kubectl cluster-info

echo "Retrieving available pods in all namespaces ...."
kubectl get pods --all-namespaces

